const data = [
"Accident Cover",
"Accidents",
"Accommodation",
"Admission",
"Age-based discount",
"Agreement hospital",
"Ambulance cover",
"Ancillary policy",
"Annual limits",
"Ante Natal - Midwife",
"APRA",
"Appliance",
"Artificial aids",
"Australian Government Rebate",
"Basic private hospital policy",
"Benefit",
"Benefit limits",
"Benefit limitation period",
"Benefits for travel & accommodation (outside of hospital)",
"Blood",
"Blood Glucose Monitors",
"Bone, joint and muscle",
"Book a doctor's appointment",
"Brain and nervous system",
"Brand",
"Bronze cover (hospital)",
"Bupa Dental",
"Bupa offers",
"Bupa Optical",
"Call-out fees",
"Call Bupa",
"Cataracts",
"Chemist delivery",
"Chemotherapy, radiotherapy and immunotherapy for cancer",
"Chinese Herbalism",
"Chiropractic & Osteopathy",
"Classification",
"Closed policy",
"Co-payment",
"Combined limit",
"Combined policy",
"Community rating",
"Compare health cover",
"Corporate health cover",
"Corporate policy",
"Cover for tax purposes",
"Covered",
"Daily excess",
"Day surgery",
"Default benefit",
"Department of Health and Aged Care",
"Dependant",
"Dietary",
"Digital Mental Health",
"Diagnostic tests",
"Drugs, dressings and other consumables",
"Ear, nose and throat",
"Elective surgery",
"Eligibility Checking System",
"Emergency Ambulance Services",
"Emergency ambulance",
"Emergency treatment",
"Examples of maximum benefits",
"Excess",
"Exclusions",
"Exercise Physiology",
"Extras",
"Extras only cover",
"Eye (not cataracts)",
"Eye Therapy",
"Family health cover",
"Find a Bupa store",
"Find a provider",
"Frequently asked questions",
"Front-end deductible",
"Fund",
"Gap",
"Gap cover arrangements",
"Gastrointestinal endoscopy",
"General Dental",
"General treatment policy",
"Get a quote",
"Gold hospital cover",
"Health aids",
"Health Aids & Appliances",
"Health insurers",
"Health Management",
"Hearing Aids",
"Heart and vascular system",
"HICAPS",
"Home nursing",
"Hospital only cover",
"Hospital and extras cover",
"Hospital psychiatric services",
"Hospital treatment for which Medicare pays no benefit",
"Implantation of hearing devices",
"Informed financial consent",
"Intensive care",
"Item number",
"Joint reconstructions",
"Joint replacements",
"Jurisdiction",
"Labour ward fees",
"Lifetime Health Cover loading (LHC)",
"Lifetime limit",
"Log in to myBupa",
"Loyalty incentive schemes",
"Lung and chest",
"Major Dental & Endodontic",
"MBS payable item",
"Medical expenses",
"Medical gap",
"Medical service",
"Medicare",
"Medicare Benefits Schedule (MBS)",
"Medicare Levy Surcharge (MLS)",
"Medicare Levy Surcharge exemption",
"Mental Health (incl. Psychology)",
"Minimum benefit",
"Monthly premium",
"Naturopathy",
"Non PBS Pharmaceuticals",
"Non-emergency ambulance",
"Not covered",
"Occupational therapy",
"Occupational Therapy",
"Online Doctor Appointments",
"Online doctors",
"Optical",
"Orthodontic",
"Out-of-pocket costs",
"Overnight excess",
"Palliative care",
"Patient moiety",
"PBS",
"Performance report",
"PHIO",
"Physiotherapy",
"Policy",
"PolicyID",
"Podiatry",
"Portability",
"Pre-existing condition",
"Preferred provider",
"Pregnancy cover",
"Premium",
"Premium discounts",
"Previous name",
"Private Health Insurance Rebate",
"Private hospital",
"Private patient in a private hospital",
"Private room",
"Product code",
"Prostheses (surgically implanted)",
"Provider",
"Psychiatric services",
"Public patient",
"Rate Rise",
"Rebate",
"Rehabilitation",
"Remedial Massage",
"Restricted access insurer",
"Restricted benefits",
"Restricted fund",
"Restricted membership insurer",
"Restrictions",
"Same-day patient",
"Shared room",
"Silver cover (hospital)",
"Singles health cover",
"Special features text",
"Speech Therapy",
"State of the Health Funds Report",
"Student health cover",
"Sub-limits",
"Suspension",
"Tax savings cover",
"Theatre fees",
"Tonsils, adenoids and grommets",
"Travel & Accommodation",
"Treatment exclusions",
"Waiting period",
"What is myBupa",
"What is Blua",
"What is the Australian Government Rebate",
"What is Lifetime Health Cover Loading (LHC)",
"What is excess",
"What are annual limits",
"Where are Bupa stores",
"Where is the closest Hospital",
"Why do my legs hurt"
];
